package closer.vlllage.com.closer

enum class ContentViewType {
    MESSAGES,
    CONTACTS,
    EVENTS,
    REVIEWS,
    PHONE_ABOUT,
    PHONE_MESSAGES,
    PHONE_PHOTOS,
    PHONE_GROUPS,
    HOME_GROUPS,
    HOME_PLACES,
    HOME_POSTS,
    HOME_ACTIVITIES,
    HOME_CALENDAR,
    HOME_FRIENDS,
    HOME_NOTIFICATIONS,
    HOME_QUESTS,
    HOME_CONTACTS,
    HOME_LIFESTYLES,
    HOME_GOALS,
    GROUP_PHOTOS,
    GROUP_ABOUT,
    HOME_WELCOME
}